### ISSUE TITLE
training on different dataset/preprosessing for increasing the resolution of output 

### ISSUE THREAD

**Issue by bhorkar** [lelechen63/ATVGnet#7]
Is there any preprocessing done on the LRW dataset?. The dataset.py directly loads the preprocessed data from basics directory.  

128x128 looks output looks decent. However, I am trying to increase the resolution of the output.

**Comment by lelechen63** [comment]
Hi there, since the purpose of this paper is not for well-looking images. We didn't add resolution options. However, you can actually modify the network (basically add one more conv layer in image encoder and one more deconv layer in image decoder) to increase the resolution. If you want to compare it with other methods which may output a higher resolution image, you can simply resize our output image by bilinear interpolation.

**Comment by lelechen63** [comment]
We do have the processed LRW dataset, but it is too large. You can also create your own dataset. The preprocessing code is in demo.py.

**Comment by 205418367** [comment]
![image](https://user-images.githubusercontent.com/47652945/58747459-35927280-849e-11e9-8db8-321ac9be63ae.png)

**Comment by 205418367** [comment]
我在运行代码时出现问题，环境配置为ubuntu18.04、python3.6、cuda9.0、pytorch0.4
![image](https://user-images.githubusercontent.com/47652945/58747489-7e4a2b80-849e-11e9-8afd-4d95689e6f6f.png)
